### PR TITLE
Remove sensio/framework-extra-bundle when using Symfony 6.2

### PR DESCRIPTION
**Pull request by nicolas-grekas**
/cc @wouterj we also remove the bundle from the doc v6.2

### CODE REVIEW

**Comment by wouterj** [comment]
> /cc @wouterj we also remove the bundle from the doc v6.2

PR is welcome :)
Seems like all leftover mentions of this bundle in 6.2 are related to the param resolver functionality that was contributed by @jderusse and you (ref https://github.com/symfony/symfony-docs/issues/17018)

**Comment by jderusse** [comment]
For a better DX, we probably first need to enable the new entity Resolver (ie. with a new parameter in Doctrine bundle)

**Comment by nicolas-grekas** [comment]
@jderusse indeed. Do you plan to work on that PR?

**Comment by jderusse** [comment]
> @jderusse indeed. Do you plan to work on that PR?

not before September

**Pull request merged**
